version: '3.1'

services:
  simpli_web:
    build:
      context: ./Simpli.SEO.Web
    image: 'ashley/simpli'
    ports:
      - "5080:80"
      - "5443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5443
    volumes:
      - D:\temp\:/root/.dotnet/https
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro